options:
  merge-default-rules: true
  formatter: stylish
files:
  include: ./src/**/*.s+(a|c)ss
rules:
  class-name-format:
    - 1
    -
      convention: hyphenatedbem
  hex-length:
    - 1
    - 
      style: long
  leading-zero: 0
  no-color-literals: 0
  property-sort-order:
    - 1
    -
      order: smacss
  no-important: 0
  shorthand-values: 0
  zero-unit: 0
  no-url-domains: 0
  no-url-protocols: 0
  nesting-depth:
    - 1
    -
      max-depth: 5
